version: '3.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=clouder02

  app:
    image: nextcloud
    restart: always
    ports:
      - 8100:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=clouder02
#      - NEXTCLOUD_ADMIN_PASSWORD=next291
#      - NEXTCLOUD_ADMIN_USER=feder1
    depends_on:
      - db

volumes:
  db:
  nextcloud:
