version: '3'

services:
  db:
    image: postgres:alpine
    container_name: nextcloud_db
    restart: always
    volumes:
      - /home/feder/docker/nextcloud/nextcloud_db:/var/lib/postgresql/data
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:apache
    container_name: nextcloud_app
    restart: always
    ports:
#      - 127.0.0.1:8200:80
      - 8200:80
    volumes:
      - /home/feder/docker/nextcloud/nextcloud_app:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:apache
    container_name: nextcloud_cron
    restart: always
    volumes:
      - /home/feder/docker/nextcloud/nextcloud_app:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  nextcloud_db:
  nextcloud_app:
