version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
#    user: uid:gid
    network_mode: "host"
    volumes:
      - config:/config
      - cache:/cache
      - /srv/movies:/media
      - /srv/music:/music
      - media2:/media2:ro
    restart: "unless-stopped"
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
volumes:
  config:
  cache:
#  media:
  media2:
