version: "3"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
#      - '67:67/udp'
      - '8080:80/tcp'
      - '8081:443/tcp'
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
    volumes:
      - './pihole/etc-pihole:/etc/pihole/'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d/'
      # run `touch ./var-log/pihole.log` first unless you like errors
      # - './var-log/pihole.log:/var/log/pihole.log'
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: '7yCY8flx1254'
      DNS1: '127.0.0.1#5053'
      DNS2: '127.0.0.1#5053'
      INTERFACE: 'eth0'
      DNSMASQ_LISTENING: 'eth0'
    restart: always
  unbound:
    container_name: unbound
    image: klutchell/unbound
    ports:
      - '5053:5053/udp'
    restart: always
  nextcloud-db:
    container_name: nextcloud-database
    image: postgres
    restart: always
    volumes:
      - nextcloud-db-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: always
    ports:
      - 8082:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=nextcloud-db-postgres
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
    depends_on:
      - nextcloud-db
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user
volumes:
  portainer:
  pihole:
  nextcloud:
  nextcloud-db-postgres:
secrets:
  nextcloud_admin_password:
    file: nextcloud_admin_password.txt # put admin password to this file
  nextcloud_admin_user:
    file: nextcloud_admin_user.txt # put admin username to this file
  postgres_db:
    file: postgres_db.txt # put postgresql db name to this file
  postgres_password:
    file: postgres_password.txt # put postgresql password to this file
  postgres_user:
    file: postgres_user.txt # put postgresql username to this file
