version: "3"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
#      - '67:67/udp'
      - '8080:80/tcp'
      - '8081:443/tcp'
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
    volumes:
      - './pihole/etc-pihole:/etc/pihole/'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d/'
      # run `touch ./var-log/pihole.log` first unless you like errors
      # - './var-log/pihole.log:/var/log/pihole.log'
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: '7yCY8flx1254'
      DNS1: '127.0.0.1#5053'
      DNS2: '127.0.0.1#5053'
      INTERFACE: 'eth0'
      DNSMASQ_LISTENING: 'eth0'
    restart: always
  unbound:
    container_name: unbound
    image: klutchell/unbound
    ports:
      - '5053:5053/udp'
    restart: always
volumes:
  portainer:
  pihole:
