
version: '3'
services:
  npm-app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - '80:80'
#      - '81:81'
      - '443:443'
#    environment:
#      - DISABLE_IPV6=true
    volumes:
      - ${DATADIR}/data:/data
      - ${DATADIR}/letsencrypt:/etc/letsencrypt
#      - ./config.json:/app/config/production.json
    networks:
      - npm-nw
      - npm-internal
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s

volumes:
  data:
  letsencrypt:

networks:
  npm-internal:
  npm-nw:
    external: true
