version: '3'
services:
  bitwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    ports:
      - 8020:80
    volumes:
      - bw-data:/data
volumes:
  bw-data:
