version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
# Also: https://github.com/chriscrowe/docker-pihole-unbound
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8180:80/tcp"
    environment:
      - TZ=${TZ:-UTC}
      - WEBPASSWORD=${WEBPASSWORD}
      - WEBTHEME=${WEBTHEME:-default-light}
#      -  ServerIP: ${ip}
      - PIHOLE_DNS_=1.1.1.1;1.0.0.1
    # Volumes store your data between container upgrades
    volumes:
      - '/home/feder/docker/pihole/etc-pihole/:/etc/pihole/'
      - '/home/feder/docker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
#    cap_add:
#      - NET_ADMIN
    restart: unless-stopped
volumes:
  etc-pihole:
  etc-dnsmasq.d:
