version: '3.2'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8580:8080
    environment:
      - TZ=Europe/Madrid
    devices:
      # Make sure this matched your adapter location
      - /dev/ttyUSB0:/dev/ttyACM0
#    group_add:
#      - dialout
#    user: 1000:1000
volumes:
  data:
